# Postgres properties
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/myBD
db.username=postgres
db.password=200420083anbooi

# Hibernate properties
hibernate.show_sql=true
hibernate.hbm2ddl.auto=create

